[package]
name = "cargo-mdparse"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
clap = "*"
pulldown-cmark = "*"
serde_derive = "*"
serde_json = "*"
serde= "*"
