name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  check-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: -f
    - run: cargo mdparse README.md -a
